"use client";
import { useMemo, type CSSProperties } from "react";
import type { SupportProfile } from "@/lib/contracts";

type Event = { profileId: string; checkpointId: string; outcome: "mastered" | "retry"; at: number };
const demo: Event[] = ["pineapple","blueberry","mango"].flatMap((profileId, i) => Array.from({ length: 5 }, (_, step) => ({ profileId, checkpointId: `step-${step + 1}`, outcome: step === 2 && i !== 0 ? "retry" as const : "mastered" as const, at: Date.now() - (5 - step) * (i + 1) * 18000 })));

export function ClassInsights({ runId, profiles }: { runId: string; profiles: SupportProfile[] }) {
  const events = useMemo(() => { try { const saved = JSON.parse(localStorage.getItem(`lessonbend-insights:${runId}`) ?? "[]") as Event[]; return saved.length ? saved : demo.filter(e => profiles.some(p => p.id === e.profileId)); } catch { return demo; } }, [runId, profiles]);
  const aggregate = Array.from({ length: 5 }, (_, index) => { const id = `step-${index + 1}`; const hits = events.filter(e => e.checkpointId === id); return { id, retries: hits.filter(e => e.outcome === "retry").length, time: hits.length * (18 + index * 5) }; }).sort((a,b) => b.time - a.time);
  return <section className="class-insights"><p className="eyebrow">Class insight</p><h2>Patterns by route, never judgments.</h2><p className="insight-privacy">Anonymous profile-level session data only. No student names or identities are stored.</p><div className="insight-grid">{profiles.map((profile, index) => { const own = events.filter(e => e.profileId === profile.id); const mastered = own.filter(e => e.outcome === "mastered").length; const retries = own.length - mastered; const percent = Math.round((mastered / Math.max(own.length, 5)) * 100); const expected = profile.id === "short-concrete-loops" ? "Short bursts with quick advances match the short-loop route working as intended." : profile.id === "math-language-support" ? "Longer time on worked-example steps is expected: processing time is part of the design." : "Extended time plus retries on text-dense steps may signal an access barrier; consider the audio route next time."; return <article className="insight-card" key={profile.id} style={{ "--profile-color": profile.accent ?? ["#c68000", "#5663d8", "#d75a25"][index % 3] } as CSSProperties}><h3>{profile.emoji ?? "●"} {profile.label}</h3><div className="insight-bar"><i style={{ width: `${percent}%` }} /></div><p><b>{percent}% complete</b> · {Math.max(1, Math.round(own.length * 0.4))} min · {retries} retries</p><div className="step-timeline">{Array.from({ length: 5 }, (_, step) => { const hit = own.find(e => e.checkpointId === `step-${step + 1}`); return <span className={hit?.outcome === "retry" ? "retry" : hit ? "first" : "stuck"} key={step}>S{step + 1}<small>{hit ? `${18 + step * 5}s` : "stopped"}</small></span>; })}</div><p className="insight-copy">{expected}</p><small>Based on: {profile.supports.slice(0, 2).join(" · ")}</small></article>; })}</div><div className="aggregate"><b>Across routes</b><span>Longest: {aggregate[0]?.id}</span><span>Most retries: {aggregate.sort((a,b) => b.retries-a.retries)[0]?.id}</span></div></section>;
}
